// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node --import tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations precisam de conexão direta (sem pooler). Em runtime, o
    // PrismaClient usa a DATABASE_URL (pooled) via adapter em lib/db.ts.
    url: process.env["DIRECT_URL"],
  },
});
